google.maps.__gjsload__('infowindow', function(_){var lI=function(a){return!!a.h.get("logAsInternal")},bAa=function(){this.h=new _.x.Set},cAa=function(a,b){if(1===a.h.size){var c=_.v(Array,"from").call(Array,_.v(a.h,"values").call(a.h))[0];c.Hk!==b.Hk&&(c.set("map",null),a.h.delete(c))}a.h.add(b)},nI=function(a){var b=this;this.W=a.Iw;this.G=null;this.Y=a.shouldFocus;this.h=_.qn("div");this.h.style.cursor="default";this.h.style.position="absolute";this.h.style.left=this.h.style.top="0";a.Pg.floatPane.appendChild(this.h);this.K=_.qn("div",this.h);
this.F=_.qn("div",this.K);this.j=_.qn("div",this.F);this.j.setAttribute("role","dialog");this.j.tabIndex=-1;this.Z=_.qn("div",this.F);this.m=_.qn("div",this.j);_.pta(this.h);_.Ym(this.j,"gm-style-iw");_.Ym(this.K,"gm-style-iw-a");_.Ym(this.F,"gm-style-iw-t");_.Ym(this.Z,"gm-style-iw-tc");_.Ym(this.j,"gm-style-iw-c");_.Ym(this.m,"gm-style-iw-d");_.Oi.h&&!_.Oi.G&&(a.Yb?this.j.style.paddingLeft=0:this.j.style.paddingRight=0,this.j.style.paddingBottom=0,this.m.style.overflow="scroll");mI(this,!1);_.Hf(this.h,
"mousedown",_.yf);_.Hf(this.h,"mouseup",_.yf);_.Hf(this.h,"mousemove",_.yf);_.Hf(this.h,"pointerdown",_.yf);_.Hf(this.h,"pointerup",_.yf);_.Hf(this.h,"pointermove",_.yf);_.Hf(this.h,"dblclick",_.yf);_.Hf(this.h,"click",_.yf);_.Hf(this.h,"touchstart",_.yf);_.Hf(this.h,"touchend",_.yf);_.Hf(this.h,"touchmove",_.yf);_.vm(this.h,"contextmenu",this,this.Vy);_.vm(this.h,"wheel",this,_.yf);_.vm(this.h,"mousewheel",this,_.vf);_.vm(this.h,"MozMousePixelScroll",this,_.vf);this.C=new _.ys({ri:new _.R(8,8),Fg:new _.Qg(14,
14),offset:new _.R(-6,-6)});this.j.appendChild(this.C.element);_.Hf(this.C.element,"click",function(c){_.yf(c);_.O(b,"closeclick");b.set("open",!1)});this.D=null;this.J=this.N=!1;this.H=new _.ui(function(){!b.N&&b.get("content")&&b.get("visible")&&(_.O(b,"domready"),b.N=!0)},0);this.V=_.Hf(this.h,"keydown",function(c){"Escape"!==c.key&&"Esc"!==c.key||!b.j.contains(document.activeElement)||(c.stopPropagation(),_.O(b,"closeclick"),b.set("open",!1))})},dAa=function(a){var b=!!a.get("open"),c=a.get("content");
c=b?c:null;if(c==a.D)mI(a,b&&a.get("position"));else{if(a.D){var d=a.D.parentNode;d==a.m&&d.removeChild(a.D)}c&&(a.N=!1,a.m.appendChild(c));mI(a,b&&a.get("position"));a.D=c;oI(a)}},eAa=function(a){var b=a.get("pixelOffset")||new _.Qg(0,0),c=new _.Qg(a.j.offsetWidth,a.j.offsetHeight);a=-b.height+c.height+11+60;var d=b.height+60,e=-b.width+c.width/2+60;c=b.width+c.width/2+60;0>b.height&&(d-=b.height);return{top:a,bottom:d,left:e,right:c}},mI=function(a,b){a.h.style.visibility=b?"":"hidden";b&&a.Y&&
(a.focus(),a.Y=!1);b?fAa(a):a.J=!1},oI=function(a){var b=a.get("layoutPixelBounds"),c=a.get("pixelOffset");var d=a.get("maxWidth")||648;var e=a.get("minWidth")||0;c?(b?(c=b.Ba-b.va-(11+-c.height),b=b.Fa-b.za-6,240<=b&&(b-=120),240<=c&&(c-=120)):(b=648,c=654),b=Math.min(b,d),b=Math.max(e,b),b=Math.max(0,b),c=Math.max(0,c),d={fe:new _.Qg(b,c),minWidth:e}):d=null;if(e=d)d=e.fe,e=e.minWidth,a.j.style.maxWidth=_.rm(d.width),a.j.style.maxHeight=_.rm(d.height),a.j.style.minWidth=_.rm(e),a.m.style.maxHeight=
_.Oi.h?_.rm(d.height-18):_.rm(d.height-36),pI(a),a.H.start()},fAa=function(a){!a.J&&a.get("open")&&a.get("visible")&&a.get("position")&&(_.O(a,"visible"),a.J=!0)},pI=function(a){var b=a.get("position");if(b&&a.get("pixelOffset")){var c=eAa(a),d=b.x-c.left,e=b.y-c.top,f=b.x+c.right;c=b.y+c.bottom;_.pn(a.K,b);b=a.get("zIndex");_.rn(a.h,_.we(b)?b:e+60);a.set("pixelBounds",_.xi(d,e,f,c))}},gAa=function(a,b){var c=a.__gm;a=c.get("panes");c=c.get("innerContainer");b={Pg:a,Yb:_.Uu.Yb(),Iw:c,shouldFocus:b};
return new nI(b)},qI=function(a,b,c){var d=this;this.H=a;this.D=!0;this.Pa=this.m=this.Ca=null;this.h=[];var e=a.get("shouldFocus");this.C=gAa(b,e);var f=b.__gm;(e=b instanceof _.Sf)&&c?c.then(function(l){d.D&&(d.Ca=l,d.Pa=new _.lE(function(m){d.m=new _.Tr(b,l,m,function(){});l.Xa(d.m);return d.m}),d.Pa.bindTo("latLngPosition",a,"position"),hAa(d))}):(this.Pa=new _.lE,this.Pa.bindTo("latLngPosition",a,"position"),this.Pa.bindTo("center",f,"projectionCenterQ"),this.Pa.bindTo("zoom",f),this.Pa.bindTo("offset",
f),this.Pa.bindTo("projection",b),this.Pa.bindTo("focus",b,"position"),hAa(this));this.F=e?lI(a)?"Ia":"Id":null;this.G=e?lI(a)?148284:148285:null;var g=new _.mE(["scale"],"visible",function(l){return null==l||.3<=l});this.Pa&&g.bindTo("scale",this.Pa);var h=this.C;h.set("logAsInternal",lI(a));h.bindTo("ariaLabel",a);h.bindTo("zIndex",a);h.bindTo("layoutPixelBounds",f,"pixelBounds");h.bindTo("disableAutoPan",a);h.bindTo("pendingFocus",a);h.bindTo("maxWidth",a);h.bindTo("minWidth",a);h.bindTo("content",
a);h.bindTo("pixelOffset",a);h.bindTo("visible",g);this.j=new _.ui(function(){if(b instanceof _.Sf)if(d.Ca){var l=a.get("position");l&&_.Sia(b,d.Ca,new _.kg(l),eAa(h))}else c.then(function(){return d.j.start()});else(l=h.get("pixelBounds"))?_.O(f,"pantobounds",l):d.j.start()},150);if(e){var k=null;this.h.push(_.wm(a,"position_changed",function(){var l=a.get("position");!l||a.get("disableAutoPan")||l.equals(k)||(d.j.start(),k=l)}))}else a.get("disableAutoPan")||this.j.start();h.set("open",!0);this.h.push(_.N(h,
"domready",function(){a.trigger("domready")}));this.h.push(_.N(h,"visible",function(){a.trigger("visible")}));this.h.push(_.N(h,"closeclick",function(){a.close();a.trigger("closeclick")}));this.h.push(_.wm(a,"pixelposition_changed",function(){iAa(d)}));this.F&&_.Eg(b,this.F);this.G&&_.Ag(b,this.G)},hAa=function(a){a.Pa&&a.h.push(_.wm(a.Pa,"pixelposition_changed",function(){iAa(a)}))},iAa=function(a){var b=a.H.get("pixelPosition")||a.Pa&&a.Pa.get("pixelPosition");a.C.set("position",b)},jAa=function(a,
b,c){return b instanceof _.Sf?new qI(a,b,c):new qI(a,b)},kAa=function(a){a=a.__gm;return a.IW_AUTO_CLOSER=a.IW_AUTO_CLOSER||new bAa};_.B(nI,_.P);_.n=nI.prototype;_.n.ariaLabel_changed=function(){var a=this.get("ariaLabel");a?this.j.setAttribute("aria-label",a):this.j.removeAttribute("aria-label")};_.n.open_changed=function(){dAa(this)};_.n.content_changed=function(){dAa(this)};
_.n.pendingFocus_changed=function(){this.get("pendingFocus")&&(this.get("open")&&this.get("visible")&&this.get("position")?_.Ri(this.j,!0):console.warn("Setting focus on InfoWindow was ignored. This is most likely due to InfoWindow not being visible yet."),this.set("pendingFocus",!1))};
_.n.dispose=function(){var a=this;setTimeout(function(){document.activeElement&&document.activeElement!==document.body||(a.G&&a.G!==document.body?_.Ri(a.G,!0)||_.Ri(a.W,!0):_.Ri(a.W,!0))});this.V&&_.Bf(this.V);this.h.parentNode.removeChild(this.h);this.H.stop();this.H.dispose()};_.n.pixelOffset_changed=function(){var a=this.get("pixelOffset")||new _.Qg(0,0);this.F.style.right=_.rm(-a.width);this.F.style.bottom=_.rm(-a.height+11);oI(this)};_.n.layoutPixelBounds_changed=function(){oI(this)};
_.n.position_changed=function(){this.get("position")?(pI(this),mI(this,!!this.get("open"))):mI(this,!1)};_.n.zIndex_changed=function(){pI(this)};_.n.visible_changed=function(){_.ay(this.h,this.get("visible"));this.H.start();if(this.get("visible")){var a=this.C.element.style.display;this.C.element.style.display="none";this.C.element.getBoundingClientRect();this.C.element.style.display=a;fAa(this)}else this.J=!1};
_.n.Vy=function(a){for(var b=!1,c=this.get("content"),d=a.target;!b&&d;)b=d==c,d=d.parentNode;b?_.vf(a):_.xf(a)};_.n.focus=function(){this.G=document.activeElement;var a;_.Oi.H&&(a=this.m.getBoundingClientRect());if(this.get("disableAutoPan"))_.Ri(this.j,!0);else{var b=_.Tga(this.m);if(b.length){b=b[0];a=a||this.m.getBoundingClientRect();var c=b.getBoundingClientRect();_.Ri(c.bottom<=a.bottom&&c.right<=a.right?b:this.j,!0)}else _.Ri(this.C.element,!0)}};qI.prototype.close=function(){if(this.D){this.D=!1;for(var a=_.A(this.h),b=a.next();!b.done;b=a.next())_.Bf(b.value);this.h.length=0;this.j.stop();this.j.dispose();this.Ca&&this.m&&this.Ca.yf(this.m);a=this.C;a.unbindAll();a.set("open",!1);a.dispose();this.Pa&&this.Pa.unbindAll()}};_.uf("infowindow",{sv:function(a){var b=null;_.wm(a,"map_changed",function d(){var e=a.get("map");b&&(b.Bq.h.delete(a),b.rz.close(),b=null);if(e){var f=e.__gm;f.get("panes")?(b={rz:jAa(a,e,e instanceof _.Sf?f.h.then(function(g){return g.Ia}):void 0),Bq:kAa(e)},cAa(b.Bq,a)):_.Kf(f,"panes_changed",d)}})}});});
